### ISSUE TITLE
What is the purpose of transform_pose_llff()?

### ISSUE THREAD

**Issue by johnnylu305** [kakaobrain/nerf-factory#10]
Hi, thank you for this work. I am recently starting using NeRF factory. It looks like transform_pose_llff() will inverse the z and y rotation matrix. Why do we need transform_pose_llff() for the llff dataset? I did not see this in load_llff.py from NeRF GitHub.

**Comment by jeongyw12382** [comment]
Sorry for being late. 
Our team members were busy for preparing the CVPR submission. 
We have integrated our coordinates to OpenCV coordinate.

https://stackoverflow.com/questions/44375149/opencv-to-opengl-coordinate-system-transform
The link above might help your understanding.

**Comment by jeongyw12382** [comment]
Let me know if you have any further questions regarding the coordinate system.

**Comment by johnnylu305** [comment]
Thanks. That helps a lot. The coordinate system is different between opencv and opengl. Everything makes sense now.

**Comment by yuemingPAN** [comment]
Hello, if the dataset is in MVSNet format and conforms to the opencv coordinate system, is there no need for transform_pose_llff()?
