### ISSUE TITLE
3D mesh generation from ckpt file

### ISSUE THREAD

**Issue by prakhar-exwzd** [kakaobrain/nerf-factory#11]
In the code we get a .ckpt model as an output. Could you let me know/point to some resource on how I can convert this model into a 3D mesh? Also would there be different mesh conversion codes for different algorithms (say nerf and mip-nerf)?

**Comment by jeongyw12382** [comment]
Sorry for being late. Our team memebers were busy for the CVPR submission.
Based on my understanding, I could provide you two distinct approaches for this:
1. When you are using models that could get explicit geometries, such as Plenoxels, DVGO,..., you could convert such geometries directly to the mesh. 
2. Unfortunately, when you are using models that are fully implicit, you could follow some work that directly regresses meshes or jointly trains the mesh model.
