### ISSUE TITLE
`self.curr_step` never increases in `LitPlenoxel`

### ISSUE THREAD

**Issue by Wuziyi616** [kakaobrain/nerf-factory#15]
Hi, thanks for releasing this great work! I think there is an error in the implementation of `LitPlenoxel`. You define `self.curr_step` [here](https://github.com/kakaobrain/NeRF-Factory/blob/ac10296a39d8e5f1940b590ca18e3689e17eadf4/src/model/plenoxel/model.py#L234) and use it to determine lr decay, voxel upsampling, etc. However, it seems that you never increase this value? I add a `print(gstep)` after [this line](https://github.com/kakaobrain/NeRF-Factory/blob/ac10296a39d8e5f1940b590ca18e3689e17eadf4/src/model/plenoxel/model.py#L310), and it always prints `0`.

**Comment by Wuziyi616** [comment]
ok so I double-check the code, [this line](https://github.com/kakaobrain/NeRF-Factory/blob/ac10296a39d8e5f1940b590ca18e3689e17eadf4/src/model/plenoxel/model.py#L314) is the only place affected by this bug, because you're reading the correct step value [here](https://github.com/kakaobrain/NeRF-Factory/blob/ac10296a39d8e5f1940b590ca18e3689e17eadf4/src/model/plenoxel/model.py#L387). All the others (lr, resolution, which are after this correct line) are not affected.

After I change [the previous line](https://github.com/kakaobrain/NeRF-Factory/blob/ac10296a39d8e5f1940b590ca18e3689e17eadf4/src/model/plenoxel/model.py#L310) to the correct one, the performance on my custom data improves a lot (I think this is because I'm using `lr_fg_begin_step>0`). As shown below, the orange curve is after correcting that line.
![image](https://user-images.githubusercontent.com/37072215/203209103-c91fc2d5-9bf2-4e7e-b5fc-5a04a2ac6098.png)

**Comment by Wuziyi616** [comment]
There is also another places affected by this, since `curr_step` is always 0, the `ResampleCallBack` condition [here](https://github.com/kakaobrain/NeRF-Factory/blob/ac10296a39d8e5f1940b590ca18e3689e17eadf4/src/model/plenoxel/model.py#L45) will never be True, so it will never upsample the Plenoxel voxel grids

**Comment by Wuziyi616** [comment]
I also have another question: the input args `near_clip` [here](https://github.com/kakaobrain/NeRF-Factory/blob/ac10296a39d8e5f1940b590ca18e3689e17eadf4/src/model/plenoxel/model.py#L184) doesn't seem to be used anywhere? I assume it should be put in `RenderOption` [here](https://github.com/kakaobrain/NeRF-Factory/blob/ac10296a39d8e5f1940b590ca18e3689e17eadf4/src/model/plenoxel/sparse_grid.py#L200). Also `background_brightness` doesn't seem to be used as well...

**Comment by jeongyw12382** [comment]
Sorry for being late. 
This issue is often found when using a different pytorch_lightning version. 
Could you share your environment version?

**Comment by jeongyw12382** [comment]
In the case of the last comment, we'll double check it and change the config if some arguments are not used.

**Comment by jeongyw12382** [comment]
Feel free to reopen the issue if you suffer from any problems regarding this issue.
