### ISSUE TITLE
Visualization tools

### ISSUE THREAD

**Issue by drinkingcoder** [kakaobrain/nerf-factory#16]
Hi, this is an awesome repository. The performance and the visualization comparison on the webpage look great. However, I didn't find the visualization code and cannot render images after training models. Do you have any suggestions?

**Comment by qiaoyaya2011** [comment]
I alse meet this problem

**Comment by jeongyw12382** [comment]
Sorry for being late. 

Have you tried the codes like below? The argument "run.run_render=True" will start rendering images. 
"""
python3 run.py --ginc configs/nerf/blender.gin --scene chair \
--ginb run.run_train=False --ginb run.run_render=True
"""

**Comment by jeongyw12382** [comment]
In the case of visualization tools that we have used in our project page, you could refer to the code here:

https://github.com/kakaobrain/NeRF-Factory/tree/gh-pages/docs/visualization

If you have any further questions or problems of building the visualization tools, let us know.

**Comment by jeongyw12382** [comment]
Feel free to reopen the issue if you face any further issues. :)
