### ISSUE TITLE
Error: RefNeRF no grad in testing

### ISSUE THREAD

**Issue by mwang625** [kakaobrain/nerf-factory#22]
Hi,

Thanks again for your great work. I got an error when evaluating RefNeRF on shiny blender dataset:
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
  In call to configurable 'run' (<function run at 0x7fe61d01fdc0>)
```
The error comes from this line: https://github.com/kakaobrain/NeRF-Factory/blob/ac10296a39d8e5f1940b590ca18e3689e17eadf4/src/model/refnerf/model.py#L153

It seems that `torch.autograd.grad` only works when backward is called but in the evaluation step there's no backpropagation. Is there anything I missed? 

Here is the command I used: 
`python3 run.py --ginc configs/refnerf/shiny_blender.gin --scene car --ginb run.run_train=False --ckpt_path logs/refnerf_shiny_blender_car_220901/best.ckpt`

Thanks in advance!

**Comment by jeongyw12382** [comment]
@seungjooshin Please check this issue.

**Comment by seungjooshin** [comment]
This error comes from the conflict of the pytorch-lightning version. We recommend `pytorch-lightning==1.7.4`, but it does not work for our Ref-NeRF implementation.
https://github.com/kakaobrain/NeRF-Factory/blob/31d74696afc89c23609e81d20c7c2eabc3f1c928/nerf_factory.yml#L205

That version uses `torch.inference_mode()` during evaluation (e.g., validate, test, and predict). However, our implementation assumes that `torch.no_grad()` is applied.

There are two options for solving this problem.

1) Change to `pytorch-lightning==1.6.0` using `pip install pytorch-lightning==1.6.0`.

2) Change to `pytorch-lightning==1.8.0` using `pip install pytorch-lightning==1.8.0` and add an option `inference_mode=False` to `Trainer()`.
https://github.com/kakaobrain/NeRF-Factory/blob/31d74696afc89c23609e81d20c7c2eabc3f1c928/run.py#L138

Thank you for your mentioning.

**Comment by mwang625** [comment]
Thanks for looking into it!
